demo/config/routes.rb
  Demo::Application.routes.draw do

   root 'posts#show'
   resources :posts

end

demo/app/models/post.rb
class Post < ActiveRecord::Base
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

demo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @akash = Post.find(params[:id])
  end

  def new
    @akash = Post.new
  end

  def create
    @akash = Post.new(params[:post].permit(:title, :text))

    @akash.save
    redirect_to @akash
  end

  def index
    @akash = Post.all
  end

end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/posts_helper.rb
module PostsHelper
end

demo/app/views/layouts/_footer.html.haml
%footer(class="footer")
  %small>
    Powered By
    %a (href="http://infibeam.com/")
      Infibeam

demo/app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %nav
        %ul.nav
          %a{href: main_app.root_path}= image_tag 'logo_transparent.png'
        %ul.nav
          - if user_signed_in?
          - else
            %li= link_to "Sign up", main_app.new_user_registration_path
            %li= link_to "Sign in", main_app.new_user_session_path

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @akash.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.text %></td>
      </tr>
  <% end %>
</table>

demo/app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

demo/app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @akash.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @akash.text %>
</p>